DROP DATABASE IF EXISTS `shop`;

CREATE DATABASE IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;



DROP USER IF EXISTS  'readonlyuser'@'%';
CREATE USER 'readonlyuser'@'%' IDENTIFIED by '123';
GRANT USAGE ON *.* TO 'readonlyuser'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT ON `shop`.* TO 'readonlyuser'@'%';

DROP USER IF EXISTS 'localuser'@'%';
CREATE USER 'localuser'@'%' IDENTIFIED by '123';
GRANT USAGE ON *.* TO 'localuser'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT, INSERT, UPDATE, DELETE ON `shop`.* TO 'localuser'@'%';

DROP USER IF EXISTS  'admin'@'%';
CREATE USER 'admin'@'%' IDENTIFIED by '123';
GRANT USAGE ON *.* TO 'admin'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `shop`.* TO 'admin'@'%' WITH GRANT OPTION;

DROP USER IF EXISTS  'shop'@'localhost';
CREATE USER 'shop'@'localhost' IDENTIFIED by '123';
GRANT USAGE ON *.* TO 'shop'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `shop`.* TO 'shop'@'localhost' WITH GRANT OPTION;
